# Seeder, Simulator ve Superset-Init için ortak taban
FROM python:3.10-slim

WORKDIR /app

# Sistem bağımlılıkları
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# Gerekli kütüphaneleri kur
RUN pip install pandas redis kafka-python requests psycopg2-binary

# Projedeki tüm dosyaları (Kodlar + Datasets) imajın içine kopyala
COPY . /app/