FROM apache/superset:latest

USER root

RUN curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    /app/.venv/bin/python get-pip.py && \
    /app/.venv/bin/python -m pip install psycopg2-binary && \
    rm get-pip.py

RUN mkdir -p /app/ozel_config
COPY Docker/superset_config.py /opt/superset_config.py
RUN chown superset:superset /opt/superset_config.py
RUN chmod 777 /opt/superset_config.py

RUN ls -la /opt/superset_config.py
USER superset